name: learnjavax
description: "Learn Java Programming - From Scratch to Master Level"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Navigation
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  lottie: ^3.1.2
  animated_text_kit: ^4.0.6
  
  # State Management
  get: ^4.6.6
  
  # Storage & Data
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.3
  
  # Text-to-Speech
  flutter_tts: ^3.8.5
  
  # Ads
  google_mobile_ads: ^5.1.0
  
  # Utils
  url_launcher: ^6.2.5
  share_plus: ^7.2.2
  flutter_local_notifications: ^17.2.2
  package_info_plus: ^8.0.2
  timezone: ^0.9.2
  
  # Code Highlighting
  flutter_highlight: ^0.7.0
  highlight: ^0.7.0
  
  # Icons
  flutter_svg: ^2.0.10+1
  
  # Connectivity
  connectivity_plus: ^6.0.5
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.9
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/animations/
    - assets/icons/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icons/icon.png"
  min_sdk_android: 21
